INSERT INTO heroes (Name, Universe, Skill, ImageURL) VALUES
('Spider-Man', 'Marvel', 'Agility, Web-shooting', 'spiderman.jpg'),
('Superman', 'DC', 'Super strength, Flight', 'superman.jpg'),
('Iron Man', 'Marvel', 'Powered armor suit', 'ironman.jpg'),
('Wonder Woman', 'DC', 'Super strength, Lasso of Truth', 'wonderwoman.jpg'),
('Black Widow', 'Marvel', 'Espionage, Martial arts', 'blackwidow.jpg'),
('Thor', 'Marvel', 'Mjolnir, Weather control', 'thor.jpg'),
('Green Lantern', 'DC', 'Power ring', 'greenlantern.jpg'),
('Captain America', 'Marvel', 'Shield throwing, Superhuman agility', 'captainamerica.jpg'),
('Hulk', 'Marvel', 'Super strength, Regeneration', 'hulk.jpg'),
('Aquaman', 'DC', 'Underwater adaptation, Superhuman strength', 'aquaman.jpg'),
('Black Panther', 'Marvel', 'Vibranium suit, Enhanced senses', 'blackpanther.jpg'),
('Flash', 'DC', 'Super speed', 'flash.jpg'),
('Doctor Strange', 'Marvel', 'Mystic arts, Time manipulation', 'doctorstrange.jpg'),
('Ant-Man', 'Marvel', 'Size manipulation, Insect communication', 'antman.jpg'),
('Wolverine', 'Marvel', 'Regeneration, Adamantium claws', 'wolverine.jpg');

INSERT INTO villains (Name, Universe, ImageURL) VALUES
('The Joker', 'DC', 'joker.jpg'),
('Loki', 'Marvel', 'loki.jpg'),
('Green Goblin', 'Marvel', 'greengoblin.jpg'),
('Lex Luthor', 'DC', 'lexluthor.jpg'),
('Magneto', 'Marvel', 'magneto.jpg'),
('Doctor Octopus', 'Marvel', 'doctoroctopus.jpg'),
('Catwoman', 'DC', 'catwoman.jpg'),
('Red Skull', 'Marvel', 'redskull.jpg'),
('Harley Quinn', 'DC', 'harleyquinn.jpg'),
('Venom', 'Marvel', 'venom.jpg'),
('Darkseid', 'DC', 'darkseid.jpg'),
('Kingpin', 'Marvel', 'kingpin.jpg'),
('Poison Ivy', 'DC', 'poisonivy.jpg'),
('Thanos', 'Marvel', 'thanos.jpg'),
('Riddler', 'DC', 'riddler.jpg');

INSERT INTO inventories (Name, Code, Stock, Description, Status) VALUES
    ("Iron Man Suit Prototype", "IM001", 10, "Replica of an Iron Man suit prototype", "active"),
    ("Captain America Shield", "CA001", 15, "Exact replica of Captain America iconic shield", "active"),
    ("Thor Hammer Mjolnir", "TH001", 5, "Miniature replica of Thor magical hammer, Mjolnir", "active"),
    ("Hulk Fist Plush Toy", "HK001", 8, "Soft plush toy shaped like Hulk giant fist", "active"),
    ("Black Widow Spy Kit", "BW001", 12, "Spy kit with gadgets similar to Black Widow", "active"),
    ("Avengers Team T-shirt", "AV001", 18, "T-shirt featuring the Avengers team logo", "active"),
    ("Wolverine Claws Replica", "WV001", 20, "Safe-to-play, retractable Wolverine claws replica", "active"),
    ("Spider-Man Web Shooter Toy", "SM001", 3, "Toy web shooter inspired by Spider-Man", "active"),
    ("Justice League Action Figures Set", "JL001", 25, "Set of action figures featuring Justice League members", "active"),
    ("Wonder Woman Lasso Replica", "WW001", 30, "Replica of Wonder Woman Lasso of Truth", "active"),
    ("Green Lantern Ring", "GL001", 7, "Green Lantern power ring replica with light effects", "active"),
    ("Aquaman Trident Prop", "AQ001", 14, "Prop replica of Aquaman iconic trident", "active"),
    ("Flash Lightning Bolt Keychain", "FL001", 9, "Keychain with Flash lightning bolt emblem", "active"),
    ("Batman Batarang Collectible", "BT001", 6, "Collectible Batarang inspired by Batman", "active"),
    ("Cyborg Robot Model Kit", "CYB001", 22, "Model kit to build a Cyborg robot", "active"),
    ("Superman Cape Costume", "SM002", 4, "Costume cape resembling Superman iconic cape", "active"),
    ("Wonder Woman Bracelet Set", "WW002", 16, "Set of Wonder Woman iconic bracelets", "active"),
    ("Green Arrow Bow and Arrow Set", "GA001", 11, "Bow and arrow set inspired by Green Arrow", "active"),
    ("Flash T-shirt", "FL002", 20, "T-shirt with the Flash emblem and lightning bolt", "active"),
    ("Justice League Poster", "JL002", 8, "Poster featuring the Justice League team", "active");
