INSERT INTO heroes (ID, Name, Universe, Skill, ImageURL) VALUES
(1, 'Spider-Man', 'Marvel', 'Agility, Web-shooting', 'spiderman.jpg'),
(2, 'Superman', 'DC', 'Super strength, Flight', 'superman.jpg'),
(3, 'Iron Man', 'Marvel', 'Powered armor suit', 'ironman.jpg'),
(4, 'Wonder Woman', 'DC', 'Super strength, Lasso of Truth', 'wonderwoman.jpg'),
(5, 'Black Widow', 'Marvel', 'Espionage, Martial arts', 'blackwidow.jpg'),
(6, 'Thor', 'Marvel', 'Mjolnir, Weather control', 'thor.jpg'),
(7, 'Green Lantern', 'DC', 'Power ring', 'greenlantern.jpg'),
(8, 'Captain America', 'Marvel', 'Shield throwing, Superhuman agility', 'captainamerica.jpg'),
(9, 'Hulk', 'Marvel', 'Super strength, Regeneration', 'hulk.jpg'),
(10, 'Aquaman', 'DC', 'Underwater adaptation, Superhuman strength', 'aquaman.jpg'),
(11, 'Black Panther', 'Marvel', 'Vibranium suit, Enhanced senses', 'blackpanther.jpg'),
(12, 'Flash', 'DC', 'Super speed', 'flash.jpg'),
(13, 'Doctor Strange', 'Marvel', 'Mystic arts, Time manipulation', 'doctorstrange.jpg'),
(14, 'Ant-Man', 'Marvel', 'Size manipulation, Insect communication', 'antman.jpg'),
(15, 'Wolverine', 'Marvel', 'Regeneration, Adamantium claws', 'wolverine.jpg');

INSERT INTO villains (ID, Name, Universe, ImageURL) VALUES
(1, 'The Joker', 'DC', 'joker.jpg'),
(2, 'Loki', 'Marvel', 'loki.jpg'),
(3, 'Green Goblin', 'Marvel', 'greengoblin.jpg'),
(4, 'Lex Luthor', 'DC', 'lexluthor.jpg'),
(5, 'Magneto', 'Marvel', 'magneto.jpg'),
(6, 'Doctor Octopus', 'Marvel', 'doctoroctopus.jpg'),
(7, 'Catwoman', 'DC', 'catwoman.jpg'),
(8, 'Red Skull', 'Marvel', 'redskull.jpg'),
(9, 'Harley Quinn', 'DC', 'harleyquinn.jpg'),
(10, 'Venom', 'Marvel', 'venom.jpg'),
(11, 'Darkseid', 'DC', 'darkseid.jpg'),
(12, 'Kingpin', 'Marvel', 'kingpin.jpg'),
(13, 'Poison Ivy', 'DC', 'poisonivy.jpg'),
(14, 'Thanos', 'Marvel', 'thanos.jpg'),
(15, 'Riddler', 'DC', 'riddler.jpg');
